---
formatter: "markdown table"

output:
  file: README.md
  mode: inject

settings:
  anchor: true
  default: true
  escape: false
  indent: 2
  required: true
  sensitive: true
  type: true

sort:
  enabled: true
  by: required

sections:
  hide: []
  show: []
